### ISSUE TITLE
Not working with 11.0

### ISSUE THREAD

**Issue by Flanell88** [erglo/wow-mission-report-button-plus#24]
Not working with TWW prepatch 11.0. Can you please update it?

**Comment by erglo** [comment]
I'm on it. There were a lot of changes to adapt, but I'm almost done. I'm trying to release a new version sometime tomorrow.

**Comment by johnson-christopher** [comment]
@erglo I have a much smaller addon that just hides the button. I thought I'd give you a head's up that it looks like something is updating the covenant callings and then after it's done it shows the button even if you've hidden it. The problem is that doesn't seem to fire any event I can find, so for mine I had to go with `C_Timer.After` inside my `COVENANT_CALLINGS_UPDATED` handler and a delay of a few seconds since it seems to take its sweet time doing it.

**Comment by erglo** [comment]
@johnson-christopher  Hi, thanks for the head's up! Unfortunately I couldn't encounter any issues in this regard. MRBP can also show or hide the minimap button.  Maybe your addon collides with this one.
I just released a new version which addresses the changes made in the pre-patch version of the game. Maybe it works now. If not, please let me know.

**Comment by erglo** [comment]
@Flanell88 Fixed and released. Enjoy!

**Comment by Farmbuyer** [comment]
Confirmed everything is working again with the 1.1.0 release.  Thank you so much!
